### ISSUE TITLE
Visual indication for query result in UI

### ISSUE THREAD

**Issue by vogti** [polypheny-db/Polypheny-DB#101]
Add an icon expressing the outcome of a query (either on the left or on the right side of the box).

![query](https://user-images.githubusercontent.com/1682115/68544521-438cdd80-03c4-11ea-8a8a-d2e92adbbc8d.PNG)

**Comment by nilshansen94** [comment]
I've had something similar in mind. But I also wanted to see the number of affected or fetched rows. I realised it with badges.
![query-results](https://user-images.githubusercontent.com/28142146/68580117-f79a7100-0475-11ea-8cd3-9c47c550120d.png)
