### ISSUE TITLE
Clean-up query result box

### ISSUE THREAD

**Issue by vogti** [polypheny-db/Polypheny-DB#68]
- Remove generated query (redundant because this is already in the header of the box)
- Only show "Affected Rows" if there is no result set

Or is there a reason to keep this information?

**Comment by nilshansen94** [comment]
The header contains only part of a query, if it is too long. Now, the generated query info will only be displayed when the query in the header is too long and cropped.
The affected-rows info was removed due to improvements made in #101 .
