### ISSUE TITLE
Specify the schema of a table when performing a table scan

### ISSUE THREAD

**Issue by nilshansen94** [polypheny-db/Polypheny-DB#79]
When performing a table scan with the plan builder, it is not yet possible to specify the schema of the table that should be scanned.

**Comment by vogti** [comment]
The scan method expects qualified names to be specified as iterable rather than as string. Please change the following line in the QueryPlanBuilder class from
`return builder.scan( node.table ).as( node.table );`
to
`return builder.scan( Util.tokenize(node.table, ".") ).as( node.table );`

**Comment by vogti** [comment]
This issue seams to be fixed. @nilshansen94 Can you confirme?

**Comment by nilshansen94** [comment]
Yes, this issue was fixed in 833fbf6b4c497c72fddcefa75c2512f4a36c837f.
