### ISSUE TITLE
Plan-Builder elements outside working area

### ISSUE THREAD

**Issue by vogti** [polypheny-db/Polypheny-DB#81]
It is possible to place plan builder elements completely or partially outside the working area.

![grafik](https://user-images.githubusercontent.com/1682115/66666362-b897b680-ec50-11e9-826d-a1b4bbeebee3.png)

**Comment by nilshansen94** [comment]
When dragging a node around, the issue is fixed.
When dropping a node for the first time, it can be partially outside, but only in a non-problematic way. Parts of the header (drag-handle) will always be in the working area.
