### ISSUE TITLE
Qualified names are not accepted in plan builder

### ISSUE THREAD

**Issue by vogti** [polypheny-db/Polypheny-DB#82]
A table scan element with public.emps results in a "Table 'public.emps' not found" message.

**Comment by vogti** [comment]
This issue seams to be fixed. @nilshansen94 Can you confirme?

**Comment by vogti** [comment]
Releated to #79

**Comment by nilshansen94** [comment]
Yes, this issue was fixed in 833fbf6b4c497c72fddcefa75c2512f4a36c837f.
